version: '3.8'
name: "global_journey"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: global_journey_fe
    restart: always
    networks:
      - my_bridge_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - backend/.env
    ports:
      - "5000:5000"
    container_name: global_journey_backend
    restart: always
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true
